lint:
	golangci-lint run ./...
	staticcheck ./...

test:
	go fmt ./internal/...
	go vet ./internal/...
	go test -v ./internal/...
	#go test -v -race -count 100 ./internal/...
	#go test -gcflags=-l -count=1 -timeout=30s -bench=. -run=^$  ./internal/...

bench:
	#go test -timeout=30s -cpuprofile=cpu.out -memprofile=mem.out -run=^$ -bench . ./...
	go test -timeout=30s -cpuprofile=cpu.out -memprofile=mem.out -bench . ./internal/service/batch/...

BUILD_DATE := $(shell date +'%Y/%m/%d %H:%M:%S')
BUILD_COMMIT := $(shell git rev-parse --short HEAD)

build:
	go build -ldflags "-X github.com/zaz600/go-musthave-shortener/internal/app.BuildVersion=v1.0.1 -X 'github.com/zaz600/go-musthave-shortener/internal/app.BuildTime=$(BUILD_DATE)' -X 'github.com/zaz600/go-musthave-shortener/internal/app.BuildCommit=$(BUILD_COMMIT)'" -o ./bin/shortener ./cmd/shortener
