lint:
	golangci-lint run ./...
	staticcheck ./...

test:
	go fmt ./internal/...
	go vet ./internal/...
	go test -v ./internal/...
	#go test -v -race -count 100 ./internal/...
	#go test -gcflags=-l -count=1 -timeout=30s -bench=. -run=^$  ./internal/...
