lint:
	golangci-lint run ./...
	staticcheck ./...

test:
	go fmt ./internal/...
	go vet ./internal/...
	go test -v ./internal/...
	#go test -v -race -count 100 ./internal/...
	#go test -gcflags=-l -count=1 -timeout=30s -bench=. -run=^$  ./internal/...

bench:
	#go test -timeout=30s -cpuprofile=cpu.out -memprofile=mem.out -run=^$ -bench . ./...
	go test -timeout=30s -cpuprofile=cpu.out -memprofile=mem.out -bench . ./internal/service/batch/...
